/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ModelRegistry } from './ModelRegistry.js';
export * as factories from './factories/index.js';
export { ModelRegistry__factory } from './factories/ModelRegistry__factory.js';